apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-nodejs: "true"
    spec:
      containers:
      - name: nest-app-backend-container
        image: durai54/torus9x-nest-app:docker_tag
        ports:
        - containerPort: 3002
        env:
        - name: redis_host
          value: "192.168.2.165"
        - name: redis_port
          value: "8085"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://l92.168.2.178:4318"
        - name: OTLP_SERVICENAME
          value: "nestjs-app"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
       - name: OTEL_EXPORTER_OTLP_TRACES_INSECURE
         value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-app
  labels:
    app: nestjs-app
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: 3002
  selector:
    app: nestjs-app
