apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-nodejs: "true"
    spec:
      containers:
      - name: nest-app-backend-container
        image: 192.168.2.164:5000/torus9x-nest-app:docker_tag
        ports:
        - containerPort: 3002
        env:
        - name: redis_host
          value: "192.168.2.165"
        - name: redis_port
          value: "8085"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://l92.168.2.178:4317"
        - name: OTLP_SERVICENAME
          value: "nestjs-app"

---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-app
  namespace: nestjs
  labels:
    app: nestjs-app
spec:
  type: NodePort
  ports:
  - port: 443
    targetPort: 3002
  selector:
    app: nestjs-app
